name: WBNRW19
channels:
  - districtdatalabs
  - r
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _r-mutex=1.0.0
  - alabaster=0.7.12
  - altair=3.2.0
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - babel=2.7.0
  - backcall=0.1.0
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - blas=1.0
  - bleach=3.1.0
  - bwidget=1.9.11
  - bzip2=1.0.8
  - ca-certificates=2019.8.28
  - cairo=1.14.12
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.7
  - curl=7.65.3
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - docutils=0.15.2
  - dropbox=9.4.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib=2.56.2
  - gmp=6.1.2
  - graphite2=1.3.13
  - gsl=2.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=1.8.8
  - icu=58.2
  - idna=2.8
  - imagesize=1.1.0
  - importlib_metadata=0.19
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - jupyterlab=1.0.2
  - jupyterlab_server=1.0.0
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - libcurl=7.65.3
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - make=4.2.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - more-itertools=7.2.0
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - nltk=3.4.5
  - notebook=6.0.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openssl=1.1.1d
  - packaging=19.1
  - pandas=0.25.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.2
  - pixman=0.38.0
  - pluggy=0.12.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - py=1.8.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pysocks=1.7.0
  - pytest=5.0.1
  - pytest-runner=5.1
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.4
  - r-acepack=1.4.1
  - r-askpass=1.1
  - r-assertive=0.3_5
  - r-assertive.base=0.0_7
  - r-assertive.code=0.0_3
  - r-assertive.data=0.0_3
  - r-assertive.data.uk=0.0_2
  - r-assertive.data.us=0.0_2
  - r-assertive.datetimes=0.0_2
  - r-assertive.files=0.0_2
  - r-assertive.matrices=0.0_2
  - r-assertive.models=0.0_2
  - r-assertive.numbers=0.0_2
  - r-assertive.properties=0.0_4
  - r-assertive.reflection=0.0_4
  - r-assertive.sets=0.0_3
  - r-assertive.strings=0.0_3
  - r-assertive.types=0.0_3
  - r-assertthat=0.2.1
  - r-backports=1.1.4
  - r-base=3.6.1
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-boot=1.3_20
  - r-broom=0.5.2
  - r-callr=3.2.0
  - r-cellranger=1.1.0
  - r-checkmate=1.9.1
  - r-cli=1.1.0
  - r-clipr=0.6.0
  - r-cluster=2.0.8
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-crosstalk=1.0.0
  - r-curl=4.0
  - r-data.table=1.12.2
  - r-dbi=1.0.0
  - r-dbplyr=1.4.0
  - r-dichromat=2.0_0
  - r-digest=0.6.20
  - r-dplyr=0.8.3
  - r-dt=0.5
  - r-ellipsis=0.2.0.1
  - r-evaluate=0.14
  - r-fansi=0.4.0
  - r-forcats=0.4.0
  - r-foreign=0.8_71
  - r-formula=1.2_3
  - r-fs=1.2.7
  - r-generics=0.0.2
  - r-ggplot2=3.1.1
  - r-glue=1.3.1
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-haven=2.1.0
  - r-highr=0.8
  - r-hmisc=4.2_0
  - r-hms=0.4.2
  - r-htmltable=1.13.1
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.3
  - r-httpuv=1.5.1
  - r-httr=1.4.1
  - r-jsonlite=1.6
  - r-knitr=1.24
  - r-labeling=0.3
  - r-later=0.8.0
  - r-lattice=0.20_38
  - r-latticeextra=0.6_28
  - r-lazyeval=0.2.2
  - r-lubridate=1.7.4
  - r-magrittr=1.5
  - r-markdown=1.1
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-mgcv=1.8_28
  - r-mime=0.7
  - r-modelr=0.1.4
  - r-munsell=0.5.0
  - r-nlme=3.1_139
  - r-nnet=7.3_12
  - r-openssl=1.3
  - r-pillar=1.4.2
  - r-pkgconfig=2.0.2
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-prettyunits=1.0.2
  - r-processx=3.3.0
  - r-progress=1.2.0
  - r-promises=1.0.1
  - r-ps=1.3.0
  - r-purrr=0.3.2
  - r-r6=2.4.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.2
  - r-rdrop2=0.8.1
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-rematch=1.0.1
  - r-reprex=0.2.1
  - r-reshape2=1.4.3
  - r-rlang=0.4.0
  - r-rmarkdown=1.12
  - r-rpart=4.1_15
  - r-rstudioapi=0.10
  - r-rtweet=0.6.9
  - r-rvest=0.3.3
  - r-scales=1.0.0
  - r-selectr=0.4_1
  - r-shiny=1.3.2
  - r-shinycssloaders=0.2.0
  - r-shinydashboard=0.7.1
  - r-shinyjs=1.0
  - r-shinywidgets=0.4.9
  - r-sourcetools=0.1.7
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - r-sys=3.3
  - r-tibble=2.1.3
  - r-tidyr=0.8.3
  - r-tidyselect=0.2.5
  - r-tidyverse=1.2.1
  - r-tinytex=0.12
  - r-utf8=1.1.4
  - r-vctrs=0.2.0
  - r-viridis=0.5.1
  - r-viridislite=0.3.0
  - r-whisker=0.3_2
  - r-withr=2.1.2
  - r-xfun=0.9
  - r-xml2=1.2.0
  - r-xtable=1.8_4
  - r-yaml=2.2.0
  - r-zeallot=0.1.0
  - readline=7.0
  - requests=2.22.0
  - scikit-learn=0.21.2
  - scipy=1.3.1
  - selenium=3.141.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - snowballstemmer=1.9.0
  - sphinx=2.1.2
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tktable=2.10
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - urllib3=1.24.2
  - vega=2.6.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - yellowbrick=1.0
  - zeromq=4.3.1
  - zipp=0.5.2
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - beautifulsoup4==4.8.0
    - blis==0.4.1
    - click==7.0
    - cymem==2.0.2
    - de-core-news-md==2.2.0
    - de-core-news-sm==2.2.0
    - deon==0.1.3
    - emoji==0.5.4
    - funcy==1.13
    - future==0.18.1
    - murmurhash==1.0.2
    - numexpr==2.7.0
    - plac==0.9.6
    - preshed==3.0.2
    - pyldavis==2.1.2
    - pyyaml==5.1.2
    - soupsieve==1.9.3
    - spacy==2.2.1
    - spacymoji==2.0.0
    - srsly==0.1.0
    - thinc==7.1.1
    - tqdm==4.36.1
    - wasabi==0.2.2
    - xerox==0.4.1

